### ISSUE TITLE
jobTemplate in CronJob should include labels in metadata

### ISSUE THREAD

**Issue by imsky** [better/kronjob#3]
```yaml
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  labels:
    kronjob/job: example-foo
  name: example-foo
  namespace: default
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 10
  jobTemplate:
   # metadata with labels should be added here
    spec:
      template:
        metadata:
          labels:
            kronjob/job: example-foo
        spec:
          containers:
          - image: scratch
            name: job
          restartPolicy: Never
  schedule: '* * * * *'
  successfulJobsHistoryLimit: 1
```
