### ISSUE TITLE
Specs with a single job should not duplicate the job name in name/labels

### ISSUE THREAD

**Issue by imsky** [better/kronjob#4]
this input:
```yaml
name: "example"
schedule: "once"
image: "scratch"
namespace: "default"
```

this produces the following output:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    kronjob/job: example-example
  name: example-example
  namespace: default
spec:
  template:
    metadata:
      labels:
        kronjob/job: example-example
    spec:
      containers:
      - image: scratch
        name: job
      restartPolicy: Never
```
