### ISSUE TITLE
Add job name to container name

### ISSUE THREAD

**Issue by imsky** [better/kronjob#5]
given this input:

```yaml
name: "example"
schedule: "once"
image: "scratch"
namespace: "default"
```

this is the output:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    kronjob/job: example-test
  name: example-test
  namespace: default
spec:
  template:
    metadata:
      labels:
        kronjob/job: example-test
    spec:
      containers:
      - image: scratch
        name: job
      restartPolicy: Never
```

container name should include job name, i.e. `example-test-job`, so that tools like LogDNA pick it up as a separate app
